#import "./ItemFragment.gql"

mutation CreateItem($name: String!, $image: String!, $price: Float!, $energy: Float!, $size: Float!) {
    CreateItem (name: $name, image: $image, price: $price, energy: $energy, size: $size) {
        ...item
    }
}