mutation CreateItem($energy: Float!, $image: String!, $name: String!, $price: Float!, $size: Float!) {
    CreateItem (energy: $energy, image: $image, name: $name, price: $price, size: $size) {
        id
        name
    }
}